// Internationalization (i18n) System
// Supports multiple languages and currencies

const i18n = {
  currentLanguage: 'en',
  currentCurrency: 'USD',
  
  translations: {
    en: {
      // General
      dealAnalyzer: 'Deal Analyzer',
      settings: 'Settings',
      save: 'Save',
      close: 'Close',
      reset: 'Reset',
      cancel: 'Cancel',
      
      // Deal Quality
      dealQuality: 'Deal Quality',
      analyzing: 'Analyzing...',
      excellent: 'Excellent',
      good: 'Good',
      fair: 'Fair',
      weak: 'Weak',
      
      // Inputs
      businessEBITDA: 'Business EBITDA',
      askingPrice: 'Asking Price',
      financingInputs: 'Financing Inputs',
      sba: 'SBA',
      percentage: 'Percentage (%)',
      loanSize: 'Loan Size ($)',
      interestRate: 'Interest Rate (%)',
      term: 'Term (Yrs)',
      targetDSCR: 'Target DSCR',
      buyerEquity: 'Buyer Equity',
      equityAmount: 'Equity Amount ($)',
      targetOwnerSalary: 'Target Owner Salary (Annual)',
      requiredForSBA: '(Required for SBA)',
      sellerNote: 'Seller Note',
      optional: '(Optional)',
      amount: 'Amount ($)',
      autoCalculated: '(Auto-calculated, override to edit)',
      standby: 'Standby',
      yes: 'Yes',
      no: 'No',
      paymentType: 'Payment Type',
      amortizing: 'Amortizing',
      interestOnly: 'Interest Only',
      
      // Results
      maximumAllowable: 'Maximum Allowable (DSCR-Based)',
      maxAllowablePurchasePrice: 'Max Allowable Purchase Price',
      maxAnnualDebtService: 'Max Annual Debt Service',
      returnOnInvestment: 'Return on Investment (Year 1)',
      cashOnCashReturn: 'Cash-on-Cash Return',
      paybackPeriod: 'Payback Period',
      years: 'years',
      freeCashFlow: 'Free Cash Flow',
      totalOwnerTakeHome: 'Total Owner Take-Home',
      actualPurchasePrice: 'Actual Purchase Price',
      targetOfferCalculator: 'Target Offer Calculator',
      calculateTargetOffer: 'Calculate Target Offer',
      toAchieveTarget: 'To achieve your {coc}% COC target, offer:',
      thisAssumes: 'This assumes:',
      askingPriceComparison: 'Asking price is {difference} than your target',
      higher: 'higher',
      lower: 'lower',
      useThisAsActualPrice: 'Use This as Actual Price',
      
      // Warnings
      sdeDetected: '⚠️ SDE detected. We subtracted $200k for Owner Salary.',
      totalPercentagesError: '⚠️ Total percentages must equal 100%',
      salaryWarning: '⚠️ Warning: Target salary exceeds available cash flow!',
      dealOpportunity: '💰 DEAL OPPORTUNITY!',
      
      // Settings
      settingsAndTargets: 'Settings & Targets',
      dealQualityTargets: 'Deal Quality Targets',
      targetCashOnCashReturn: 'Target Cash-on-Cash Return (%)',
      targetCashOnCashReturnDesc: 'Your minimum acceptable annual return on equity investment',
      targetPaybackPeriod: 'Target Payback Period (Years)',
      targetPaybackPeriodDesc: 'Maximum years to recover your initial equity investment',
      displayPreferences: 'Display Preferences',
      useCompactFormat: 'Use compact number format (1.2M instead of 1,200,000)',
      darkMode: 'Dark Mode',
      language: 'Language',
      currency: 'Currency',
      saveSettings: '💾 Save Settings',
      resetDefaults: '↺ Reset Defaults',
      
      // Deal Notes
      dealNotes: 'Deal Notes',
      addNotes: 'Add notes: questions for seller, red flags, follow-ups, pros/cons...',
      
      // Actions
      saveDeal: 'Save current deal (Cmd/Ctrl+S)',
      openDashboard: 'Open Deals Dashboard',
      buyCoffee: 'Buy me a coffee ☕ ($10)',
      scrapingDiagnostics: 'Scraping Diagnostics',
      
      // Summary
      summary: 'Summary',
      sbaLoan: 'SBA Loan',
      buyerEquityAmount: 'Buyer Equity',
      sellerNoteAmount: 'Seller Note',
      totalFinancing: 'Total Financing',
      at: 'at',
      
      // PDF Export
      generatedBy: 'Generated by Max Price Deal Analyzer',
    },
    
    es: {
      dealAnalyzer: 'Analizador de Ofertas',
      settings: 'Configuración',
      save: 'Guardar',
      close: 'Cerrar',
      reset: 'Restablecer',
      cancel: 'Cancelar',
      dealQuality: 'Calidad de Oferta',
      analyzing: 'Analizando...',
      excellent: 'Excelente',
      good: 'Bueno',
      fair: 'Regular',
      weak: 'Débil',
      businessEBITDA: 'EBITDA del Negocio',
      askingPrice: 'Precio de Venta',
      financingInputs: 'Entradas de Financiación',
      sba: 'SBA',
      percentage: 'Porcentaje (%)',
      loanSize: 'Tamaño del Préstamo ($)',
      interestRate: 'Tasa de Interés (%)',
      term: 'Plazo (Años)',
      targetDSCR: 'DSCR Objetivo',
      buyerEquity: 'Capital del Comprador',
      equityAmount: 'Cantidad de Capital ($)',
      targetOwnerSalary: 'Salario Objetivo del Propietario (Anual)',
      requiredForSBA: '(Requerido para SBA)',
      sellerNote: 'Nota del Vendedor',
      optional: '(Opcional)',
      amount: 'Cantidad ($)',
      autoCalculated: '(Auto-calculado, sobrescribir para editar)',
      standby: 'En Espera',
      yes: 'Sí',
      no: 'No',
      paymentType: 'Tipo de Pago',
      amortizing: 'Amortización',
      interestOnly: 'Solo Interés',
      maximumAllowable: 'Máximo Permitido (Basado en DSCR)',
      maxAllowablePurchasePrice: 'Precio Máximo de Compra Permitido',
      maxAnnualDebtService: 'Servicio de Deuda Anual Máximo',
      returnOnInvestment: 'Retorno de Inversión (Año 1)',
      cashOnCashReturn: 'Retorno de Efectivo sobre Efectivo',
      paybackPeriod: 'Período de Recuperación',
      years: 'años',
      freeCashFlow: 'Flujo de Efectivo Libre',
      totalOwnerTakeHome: 'Total del Propietario',
      actualPurchasePrice: 'Precio de Compra Real',
      targetOfferCalculator: 'Calculadora de Oferta Objetivo',
      calculateTargetOffer: 'Calcular Oferta Objetivo',
      toAchieveTarget: 'Para lograr tu objetivo de {coc}% COC, ofrece:',
      thisAssumes: 'Esto asume:',
      askingPriceComparison: 'El precio de venta es {difference} que tu objetivo',
      higher: 'mayor',
      lower: 'menor',
      useThisAsActualPrice: 'Usar Esto como Precio Real',
      sdeDetected: '⚠️ SDE detectado. Restamos $200k por Salario del Propietario.',
      totalPercentagesError: '⚠️ Los porcentajes totales deben ser iguales al 100%',
      salaryWarning: '⚠️ Advertencia: ¡El salario objetivo excede el flujo de efectivo disponible!',
      dealOpportunity: '💰 ¡OPORTUNIDAD DE OFERTA!',
      settingsAndTargets: 'Configuración y Objetivos',
      dealQualityTargets: 'Objetivos de Calidad de Oferta',
      targetCashOnCashReturn: 'Retorno Objetivo de Efectivo sobre Efectivo (%)',
      targetCashOnCashReturnDesc: 'Tu retorno anual mínimo aceptable sobre la inversión de capital',
      targetPaybackPeriod: 'Período de Recuperación Objetivo (Años)',
      targetPaybackPeriodDesc: 'Años máximos para recuperar tu inversión inicial de capital',
      displayPreferences: 'Preferencias de Visualización',
      useCompactFormat: 'Usar formato de número compacto (1.2M en lugar de 1,200,000)',
      darkMode: 'Modo Oscuro',
      language: 'Idioma',
      currency: 'Moneda',
      saveSettings: '💾 Guardar Configuración',
      resetDefaults: '↺ Restablecer Valores Predeterminados',
      dealNotes: 'Notas de Oferta',
      addNotes: 'Agregar notas: preguntas para el vendedor, banderas rojas, seguimientos, pros/contras...',
      saveDeal: 'Guardar oferta actual (Cmd/Ctrl+S)',
      openDashboard: 'Abrir Panel de Ofertas',
      buyCoffee: 'Cómprame un café ☕ ($10)',
      scrapingDiagnostics: 'Diagnósticos de Extracción',
      summary: 'Resumen',
      sbaLoan: 'Préstamo SBA',
      buyerEquityAmount: 'Capital del Comprador',
      sellerNoteAmount: 'Nota del Vendedor',
      totalFinancing: 'Financiación Total',
      at: 'a',
      generatedBy: 'Generado por Analizador de Precio Máximo de Oferta',
    },
    
    fr: {
      dealAnalyzer: 'Analyseur d\'Offres',
      settings: 'Paramètres',
      save: 'Enregistrer',
      close: 'Fermer',
      reset: 'Réinitialiser',
      cancel: 'Annuler',
      dealQuality: 'Qualité de l\'Offre',
      analyzing: 'Analyse en cours...',
      excellent: 'Excellent',
      good: 'Bon',
      fair: 'Moyen',
      weak: 'Faible',
      businessEBITDA: 'EBITDA de l\'Entreprise',
      askingPrice: 'Prix Demandé',
      financingInputs: 'Entrées de Financement',
      sba: 'SBA',
      percentage: 'Pourcentage (%)',
      loanSize: 'Montant du Prêt ($)',
      interestRate: 'Taux d\'Intérêt (%)',
      term: 'Durée (Ans)',
      targetDSCR: 'DSCR Cible',
      buyerEquity: 'Capitaux Propres de l\'Acheteur',
      equityAmount: 'Montant des Capitaux Propres ($)',
      targetOwnerSalary: 'Salaire Cible du Propriétaire (Annuel)',
      requiredForSBA: '(Requis pour SBA)',
      sellerNote: 'Note du Vendeur',
      optional: '(Optionnel)',
      amount: 'Montant ($)',
      autoCalculated: '(Auto-calculé, remplacer pour modifier)',
      standby: 'En Attente',
      yes: 'Oui',
      no: 'Non',
      paymentType: 'Type de Paiement',
      amortizing: 'Amortissement',
      interestOnly: 'Intérêts Seulement',
      maximumAllowable: 'Maximum Autorisé (Basé sur DSCR)',
      maxAllowablePurchasePrice: 'Prix d\'Achat Maximum Autorisé',
      maxAnnualDebtService: 'Service de Dette Annuel Maximum',
      returnOnInvestment: 'Retour sur Investissement (Année 1)',
      cashOnCashReturn: 'Retour sur Trésorerie',
      paybackPeriod: 'Période de Récupération',
      years: 'ans',
      freeCashFlow: 'Flux de Trésorerie Libre',
      totalOwnerTakeHome: 'Total du Propriétaire',
      actualPurchasePrice: 'Prix d\'Achat Réel',
      targetOfferCalculator: 'Calculateur d\'Offre Cible',
      calculateTargetOffer: 'Calculer l\'Offre Cible',
      toAchieveTarget: 'Pour atteindre votre objectif de {coc}% COC, offrez:',
      thisAssumes: 'Cela suppose:',
      askingPriceComparison: 'Le prix demandé est {difference} que votre objectif',
      higher: 'supérieur',
      lower: 'inférieur',
      useThisAsActualPrice: 'Utiliser Ceci comme Prix Réel',
      sdeDetected: '⚠️ SDE détecté. Nous avons soustrait 200k$ pour le Salaire du Propriétaire.',
      totalPercentagesError: '⚠️ Les pourcentages totaux doivent être égaux à 100%',
      salaryWarning: '⚠️ Avertissement: Le salaire cible dépasse le flux de trésorerie disponible!',
      dealOpportunity: '💰 OPPORTUNITÉ D\'OFFRE!',
      settingsAndTargets: 'Paramètres et Objectifs',
      dealQualityTargets: 'Objectifs de Qualité d\'Offre',
      targetCashOnCashReturn: 'Retour sur Trésorerie Cible (%)',
      targetCashOnCashReturnDesc: 'Votre retour annuel minimum acceptable sur l\'investissement en capitaux propres',
      targetPaybackPeriod: 'Période de Récupération Cible (Ans)',
      targetPaybackPeriodDesc: 'Années maximum pour récupérer votre investissement initial en capitaux propres',
      displayPreferences: 'Préférences d\'Affichage',
      useCompactFormat: 'Utiliser le format de nombre compact (1.2M au lieu de 1,200,000)',
      darkMode: 'Mode Sombre',
      language: 'Langue',
      currency: 'Devise',
      saveSettings: '💾 Enregistrer les Paramètres',
      resetDefaults: '↺ Réinitialiser les Valeurs par Défaut',
      dealNotes: 'Notes sur l\'Offre',
      addNotes: 'Ajouter des notes: questions pour le vendeur, drapeaux rouges, suivis, avantages/inconvénients...',
      saveDeal: 'Enregistrer l\'offre actuelle (Cmd/Ctrl+S)',
      openDashboard: 'Ouvrir le Tableau de Bord des Offres',
      buyCoffee: 'M\'offrir un café ☕ ($10)',
      scrapingDiagnostics: 'Diagnostics d\'Extraction',
      summary: 'Résumé',
      sbaLoan: 'Prêt SBA',
      buyerEquityAmount: 'Capitaux Propres de l\'Acheteur',
      sellerNoteAmount: 'Note du Vendeur',
      totalFinancing: 'Financement Total',
      at: 'à',
      generatedBy: 'Généré par Analyseur de Prix Maximum d\'Offre',
    },
    
    de: {
      dealAnalyzer: 'Deal-Analysator',
      settings: 'Einstellungen',
      save: 'Speichern',
      close: 'Schließen',
      reset: 'Zurücksetzen',
      cancel: 'Abbrechen',
      dealQuality: 'Deal-Qualität',
      analyzing: 'Analysiere...',
      excellent: 'Ausgezeichnet',
      good: 'Gut',
      fair: 'Mäßig',
      weak: 'Schwach',
      businessEBITDA: 'Geschäfts-EBITDA',
      askingPrice: 'Verkaufspreis',
      financingInputs: 'Finanzierungseingaben',
      sba: 'SBA',
      percentage: 'Prozentsatz (%)',
      loanSize: 'Darlehensbetrag ($)',
      interestRate: 'Zinssatz (%)',
      term: 'Laufzeit (Jahre)',
      targetDSCR: 'Ziel-DSCR',
      buyerEquity: 'Eigenkapital des Käufers',
      equityAmount: 'Eigenkapitalbetrag ($)',
      targetOwnerSalary: 'Zielgehalt des Eigentümers (Jährlich)',
      requiredForSBA: '(Erforderlich für SBA)',
      sellerNote: 'Verkäufernotiz',
      optional: '(Optional)',
      amount: 'Betrag ($)',
      autoCalculated: '(Automatisch berechnet, überschreiben zum Bearbeiten)',
      standby: 'Standby',
      yes: 'Ja',
      no: 'Nein',
      paymentType: 'Zahlungsart',
      amortizing: 'Tilgung',
      interestOnly: 'Nur Zinsen',
      maximumAllowable: 'Maximal Zulässig (DSCR-basiert)',
      maxAllowablePurchasePrice: 'Maximal zulässiger Kaufpreis',
      maxAnnualDebtService: 'Maximaler jährlicher Schuldendienst',
      returnOnInvestment: 'Kapitalrendite (Jahr 1)',
      cashOnCashReturn: 'Cash-on-Cash-Rendite',
      paybackPeriod: 'Amortisationszeit',
      years: 'Jahre',
      freeCashFlow: 'Freier Cashflow',
      totalOwnerTakeHome: 'Gesamtes Eigentümer-Einkommen',
      actualPurchasePrice: 'Tatsächlicher Kaufpreis',
      targetOfferCalculator: 'Zielangebotsrechner',
      calculateTargetOffer: 'Zielangebot berechnen',
      toAchieveTarget: 'Um Ihr {coc}% COC-Ziel zu erreichen, bieten Sie:',
      thisAssumes: 'Dies setzt voraus:',
      askingPriceComparison: 'Der Verkaufspreis ist {difference} als Ihr Ziel',
      higher: 'höher',
      lower: 'niedriger',
      useThisAsActualPrice: 'Dies als tatsächlichen Preis verwenden',
      sdeDetected: '⚠️ SDE erkannt. Wir haben 200k$ für Eigentümergehalt abgezogen.',
      totalPercentagesError: '⚠️ Die Gesamtprozentsätze müssen 100% entsprechen',
      salaryWarning: '⚠️ Warnung: Das Zielgehalt übersteigt den verfügbaren Cashflow!',
      dealOpportunity: '💰 DEAL-GELEGENHEIT!',
      settingsAndTargets: 'Einstellungen & Ziele',
      dealQualityTargets: 'Deal-Qualitätsziele',
      targetCashOnCashReturn: 'Ziel Cash-on-Cash-Rendite (%)',
      targetCashOnCashReturnDesc: 'Ihre minimal akzeptable jährliche Rendite auf Eigenkapitalinvestition',
      targetPaybackPeriod: 'Ziel-Amortisationszeit (Jahre)',
      targetPaybackPeriodDesc: 'Maximale Jahre zur Rückgewinnung Ihrer anfänglichen Eigenkapitalinvestition',
      displayPreferences: 'Anzeigeeinstellungen',
      useCompactFormat: 'Kompaktes Zahlenformat verwenden (1.2M statt 1,200,000)',
      darkMode: 'Dunkelmodus',
      language: 'Sprache',
      currency: 'Währung',
      saveSettings: '💾 Einstellungen speichern',
      resetDefaults: '↺ Standardwerte zurücksetzen',
      dealNotes: 'Deal-Notizen',
      addNotes: 'Notizen hinzufügen: Fragen für den Verkäufer, Warnsignale, Nachfassaktionen, Vor-/Nachteile...',
      saveDeal: 'Aktuelles Angebot speichern (Cmd/Ctrl+S)',
      openDashboard: 'Deal-Dashboard öffnen',
      buyCoffee: 'Kauf mir einen Kaffee ☕ ($10)',
      scrapingDiagnostics: 'Scraping-Diagnose',
      summary: 'Zusammenfassung',
      sbaLoan: 'SBA-Darlehen',
      buyerEquityAmount: 'Eigenkapital des Käufers',
      sellerNoteAmount: 'Verkäufernotiz',
      totalFinancing: 'Gesamtfinanzierung',
      at: 'bei',
      generatedBy: 'Erstellt von Max Price Deal Analyzer',
    },
  },
  
  currencies: {
    USD: { symbol: '$', code: 'USD', name: 'US Dollar' },
    EUR: { symbol: '€', code: 'EUR', name: 'Euro' },
    GBP: { symbol: '£', code: 'GBP', name: 'British Pound' },
    CAD: { symbol: 'C$', code: 'CAD', name: 'Canadian Dollar' },
    AUD: { symbol: 'A$', code: 'AUD', name: 'Australian Dollar' },
    JPY: { symbol: '¥', code: 'JPY', name: 'Japanese Yen' },
    MXN: { symbol: 'MX$', code: 'MXN', name: 'Mexican Peso' },
    CHF: { symbol: 'CHF', code: 'CHF', name: 'Swiss Franc' },
  },
  
  // Get translation for a key
  t(key, params = {}) {
    const translation = this.translations[this.currentLanguage]?.[key] || 
                       this.translations.en[key] || 
                       key;
    
    // Replace parameters like {coc} with actual values
    return translation.replace(/\{(\w+)\}/g, (match, paramKey) => {
      return params[paramKey] !== undefined ? params[paramKey] : match;
    });
  },
  
  // Format currency
  formatCurrency(amount, currency = null) {
    const curr = currency || this.currentCurrency;
    const currencyInfo = this.currencies[curr] || this.currencies.USD;
    const symbol = currencyInfo.symbol;
    
    // Format number based on locale
    const locale = this.getLocaleForCurrency(curr);
    const formatted = new Intl.NumberFormat(locale, {
      minimumFractionDigits: 0,
      maximumFractionDigits: 0,
    }).format(amount);
    
    return `${symbol}${formatted}`;
  },
  
  // Get locale for currency
  getLocaleForCurrency(currency) {
    const localeMap = {
      USD: 'en-US',
      EUR: 'de-DE',
      GBP: 'en-GB',
      CAD: 'en-CA',
      AUD: 'en-AU',
      JPY: 'ja-JP',
      MXN: 'es-MX',
      CHF: 'de-CH',
    };
    return localeMap[currency] || 'en-US';
  },
  
  // Set language
  setLanguage(lang) {
    if (this.translations[lang]) {
      this.currentLanguage = lang;
      return true;
    }
    return false;
  },
  
  // Set currency
  setCurrency(currency) {
    if (this.currencies[currency]) {
      this.currentCurrency = currency;
      return true;
    }
    return false;
  },
  
  // Get available languages
  getAvailableLanguages() {
    return Object.keys(this.translations).map(code => ({
      code,
      name: this.getLanguageName(code),
    }));
  },
  
  // Get language name
  getLanguageName(code) {
    const names = {
      en: 'English',
      es: 'Español',
      fr: 'Français',
      de: 'Deutsch',
    };
    return names[code] || code;
  },
  
  // Get available currencies
  getAvailableCurrencies() {
    return Object.values(this.currencies);
  },
};

// Make i18n available globally
if (typeof window !== 'undefined') {
  window.i18n = i18n;
}
