# -*- coding: utf-8 -*-
"""Google Sheet Deal Parser

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aQ3uLtRGI2YWbfW6-KpJcxgtqbDku8yv
"""

import os
import pickle
from googleapiclient.discovery import build
from google_auth_oauthlib.flow import InstalledAppFlow
from google.auth.transport.requests import Request

# Configuration
SPREADSHEET_ID = '1BRxqznJiNw08Rrq0HF-eGqAg7lREkpsnhhXIkyV9BRw'
# Ensure the range includes all columns (A to Z or specific ones like A:G)
RANGE_NAME = 'On-Market!A1:Z500'
SCOPES = ['https://www.googleapis.com/auth/spreadsheets.readonly']

def get_google_sheets_service():
    creds = None
    if os.path.exists('token.pickle'):
        with open('token.pickle', 'rb') as token:
            creds = pickle.load(token)

    if not creds or not creds.valid:
        if creds and creds.expired and creds.refresh_token:
            creds.refresh(Request())
        else:
            flow = InstalledAppFlow.from_client_secrets_file('credentials.json', SCOPES)
            creds = flow.run_local_server(port=0)
        with open('token.pickle', 'wb') as token:
            pickle.dump(creds, token)

    return build('sheets', 'v4', credentials=creds)

def fetch_deals_to_scrape():
    service = get_google_sheets_service()

    # Requesting specific fields is the 'secret sauce' for getting hidden URLs
    request = service.spreadsheets().get(
        spreadsheetId=SPREADSHEET_ID,
        ranges=[RANGE_NAME],
        fields="sheets(data(rowData(values(hyperlink,formattedValue))))"
    )
    response = request.execute()

    rows = response['sheets'][0]['data'][0].get('rowData', [])
    if not rows:
        return []

    # 1. Parse Headers (first row)
    header_row = rows[0].get('values', [])
    headers = [cell.get('formattedValue', f'col_{i}') for i, cell in enumerate(header_row)]

    parsed_deals = []

    # 2. Parse Data Rows
    for row_data in rows[1:]:
        cells = row_data.get('values', [])
        deal_obj = {}

        for i, cell in enumerate(cells):
            if i >= len(headers): break

            header_name = headers[i]
            display_text = cell.get('formattedValue', "")
            link = cell.get('hyperlink', None)

            # If a link exists, we store it specifically.
            # You can store it as a separate key or override the display text
            deal_obj[header_name] = display_text
            if link:
                deal_obj[f"{header_name}_url"] = link

        if deal_obj: # Avoid empty rows
            parsed_deals.append(deal_obj)

    return parsed_deals

if __name__ == "__main__":
    # This list is now ready to be passed to your scraper
    deals = fetch_deals_to_scrape()

    for deal in deals:
        # Example: if your header is "Deal Link", the URL will be in "Deal Link_url"
        # or whichever column contains the "view listing here" text.
        print(f"Processing: {deal.get('Deal name', 'Unknown')}")
        print(f"Link found: {deal.get('Link to Deal_url') or deal.get('Source_url')}")